// <auto-generated />
namespace JordanSky.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updat_hotl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updat_hotl));
        
        string IMigrationMetadata.Id
        {
            get { return "202106151152051_updat_hotl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
